// engine.js — The Mystery of Brita Svani
// Game engine. Do not edit this file. All content lives in scenes.js.

const STATE = {
  currentScene: null,
  inventory: [],
  removedProps: {},   // tracks which props have been picked up, per scene
  editorMode: false,
  dialogueOpen: false,
  inventoryOpen: false,
  lightboxOpen: false,
  musicEnabled: true,
  musicVolume: 0.5,
};

// ─── AUDIO ───────────────────────────────────────────────────────────────────

const bgMusic = new Audio("assets/audio/score.mp3");
bgMusic.loop = true;
bgMusic.volume = STATE.musicVolume;

function startMusic() {
  if (STATE.musicEnabled) bgMusic.play().catch(() => {});
}

function setMusicEnabled(val) {
  STATE.musicEnabled = val;
  val ? bgMusic.play().catch(() => {}) : bgMusic.pause();
  updateSettingsUI();
}

function setMusicVolume(val) {
  STATE.musicVolume = val;
  bgMusic.volume = val;
  updateSettingsUI();
}

// ─── INIT ────────────────────────────────────────────────────────────────────

function startGame() {
  document.getElementById("title-screen").style.display = "none";
  document.getElementById("top-bar").style.display = "flex";
  document.getElementById("inventory-btn").style.display = "flex";
  loadScene("cabin");
  fadeIn();
  startMusic();
}

function loadScene(sceneId) {
  const scene = SCENES[sceneId];
  if (!scene) { console.error("Scene not found:", sceneId); return; }
  STATE.currentScene = scene;

  document.getElementById("background").src = scene.background;
  document.getElementById("scene-label").textContent = scene.name;

  closeInventory();
  closeLightbox();
  renderProps(scene);
  renderHotspots(scene);
  renderInventory();
}

// ─── PROPS ───────────────────────────────────────────────────────────────────
// Props are image stickers layered on top of the background.
// They are removed when picked up and that state is remembered.

// Calculate the visible crop rect of the background image under object-fit:cover.
// Returns { offsetX, offsetY, visibleW, visibleH } in pixels — the portion of the
// background coordinate space that maps to the viewport.
function getCoverRect() {
  const vw = window.innerWidth;
  const vh = window.innerHeight;
  const bg = document.getElementById("background");
  const nw = bg.naturalWidth  || 1920;
  const nh = bg.naturalHeight || 1080;

  const scaleW = vw / nw;
  const scaleH = vh / nh;
  const scale  = Math.max(scaleW, scaleH); // cover = largest scale

  const renderedW = nw * scale;
  const renderedH = nh * scale;

  // The image is centered; calculate how much is cropped on each side
  const offsetX = (renderedW - vw) / 2;
  const offsetY = (renderedH - vh) / 2;

  return { offsetX, offsetY, renderedW, renderedH, scale };
}

// Convert a background-space % position (same coordinate system as hotspots)
// into viewport px, accounting for object-fit: cover cropping.
function bgPctToViewportPx(xPct, yPct, wPct, hPct) {
  const { offsetX, offsetY, renderedW, renderedH } = getCoverRect();
  const left   = (xPct / 100) * renderedW - offsetX;
  const top    = (yPct / 100) * renderedH - offsetY;
  const width  = (wPct / 100) * renderedW;
  const height = (hPct / 100) * renderedH;
  return { left, top, width, height };
}

function positionProp(el, prop) {
  const { left, top, width, height } = bgPctToViewportPx(prop.x, prop.y, prop.width, prop.height);
  el.style.left   = left   + "px";
  el.style.top    = top    + "px";
  el.style.width  = width  + "px";
  el.style.height = height + "px";
}

function renderProps(scene) {
  const layer = document.getElementById("prop-layer");
  layer.innerHTML = "";
  if (!scene.props) return;

  const removed = STATE.removedProps[scene.id] || {};

  scene.props.forEach(prop => {
    if (removed[prop.id]) return;

    const el = document.createElement("img");
    el.src = prop.image + "?v=" + Date.now();
    el.id = "prop-" + prop.id;
    el.style.cssText = `
      position: absolute;
      pointer-events: none;
    `;
    positionProp(el, prop);
    el.onload = () => positionProp(el, prop);
    layer.appendChild(el);
  });
}

// Re-position all props when window resizes
window.addEventListener("resize", () => {
  const scene = STATE.currentScene;
  if (!scene || !scene.props) return;
  const removed = STATE.removedProps[scene.id] || {};
  scene.props.forEach(prop => {
    if (removed[prop.id]) return;
    const el = document.getElementById("prop-" + prop.id);
    if (el) positionProp(el, prop);
  });
});

function removeProp(sceneId, propId) {
  if (!STATE.removedProps[sceneId]) STATE.removedProps[sceneId] = {};
  STATE.removedProps[sceneId][propId] = true;

  const el = document.getElementById("prop-" + propId);
  if (el) {
    el.style.transition = "opacity 0.35s ease";
    el.style.opacity = "0";
    setTimeout(() => el.remove(), 360);
  }
}

// ─── HOTSPOTS ────────────────────────────────────────────────────────────────

function renderHotspots(scene) {
  const layer = document.getElementById("hotspot-layer");
  layer.innerHTML = "";
  scene.hotspots.forEach(hs => {
    const el = document.createElement("div");
    el.className = "hotspot" + (STATE.editorMode ? " debug" : "");
    el.style.cssText = `left:${hs.x}%;top:${hs.y}%;width:${hs.width}%;height:${hs.height}%`;
    el.dataset.id = hs.id;

    const label = document.createElement("div");
    label.className = "hotspot-label";
    label.textContent = hs.label;
    el.appendChild(label);

    el.addEventListener("click", () => {
      if (STATE.editorMode) return;
      triggerHotspot(hs);
    });

    layer.appendChild(el);
  });
}

function triggerHotspot(hs) {
  const action = hs.action;
  if (!action) return;

  if (action.type === "dialogue") {
    showDialogue(action.speaker, action.text);

  } else if (action.type === "pickup") {
    const alreadyHave = STATE.inventory.find(i => i.id === action.item.id);
    if (!alreadyHave) {
      STATE.inventory.push(action.item);
      renderInventory();
      showPickupNotification(action.item.label);
      // Remove the visual prop from the scene
      if (action.removesProp) {
        removeProp(STATE.currentScene.id, action.removesProp);
      }
      // Hide this hotspot too so you can't click empty air
      const hotspotEl = document.querySelector(`[data-id="${hs.id}"]`);
      if (hotspotEl) hotspotEl.style.display = "none";
      showDialogue(action.speaker, action.text);
    } else {
      showDialogue(action.speaker, action.alreadyTaken || "I already have that.");
    }

  } else if (action.type === "scene") {
    closeInventory();
    closeLightbox();
    fadeOut(() => { loadScene(action.target); fadeIn(); });

  } else if (action.type === "lightbox") {
    openLightbox(action.image, action.eyeTracking);

  } else if (action.type === "conditional") {
    const hasItem = STATE.inventory.find(i => i.id === action.requiresItem);
    if (hasItem) {
      showDialogue(action.speaker, action.textSuccess);
      if (action.then) setTimeout(() => handleThen(action.then), 1800);
    } else {
      showDialogue(action.speaker, action.textFail);
    }
  }
}

function handleThen(then) {
  if (then.type === "scene") {
    fadeOut(() => { loadScene(then.target); fadeIn(); });
  } else if (then.type === "pickup") {
    if (!STATE.inventory.find(i => i.id === then.item.id)) {
      STATE.inventory.push(then.item);
      renderInventory();
    }
  }
}

// ─── LIGHTBOX (cat portrait + eye tracking) ──────────────────────────────────

let eyeTrackingActive = false;

function openLightbox(imageSrc) {
  STATE.lightboxOpen = true;
  closeDialogue();
  closeInventory();

  const lb = document.getElementById("lightbox");
  const img = document.getElementById("lightbox-img");

  img.src = imageSrc;
  lb.style.display = "flex";
  requestAnimationFrame(() => lb.classList.add("open"));
}

function closeLightbox() {
  STATE.lightboxOpen = false;
  eyeTrackingActive = false;
  const lb = document.getElementById("lightbox");
  lb.classList.remove("open");
  setTimeout(() => { lb.style.display = "none"; }, 280);
}

// ─── DIALOGUE ────────────────────────────────────────────────────────────────

function showDialogue(speaker, text) {
  STATE.dialogueOpen = true;
  closeInventory();
  document.getElementById("dialogue-speaker").textContent = speaker || "—";
  document.getElementById("dialogue-text").textContent = text;
  document.getElementById("dialogue-box").style.display = "block";
}

function closeDialogue() {
  STATE.dialogueOpen = false;
  document.getElementById("dialogue-box").style.display = "none";
}

// ─── INVENTORY ───────────────────────────────────────────────────────────────

const ITEM_ICONS = {
  mystery_bottle: `
    <svg viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M8 2 h6 v3 l2 3 v10 a1.5 1.5 0 0 1-1.5 1.5 h-5 a1.5 1.5 0 0 1-1.5-1.5 V8 l2-3 Z"
            stroke="rgba(200,170,90,0.85)" stroke-width="1.3" fill="rgba(200,170,90,0.08)"/>
      <line x1="7.5" y1="11" x2="14.5" y2="11" stroke="rgba(200,170,90,0.45)" stroke-width="1"/>
      <rect x="8.5" y="2" width="5" height="1.5" rx="0.5"
            stroke="rgba(200,170,90,0.65)" stroke-width="1" fill="none"/>
    </svg>`,
  note: `
    <svg viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
      <rect x="4" y="2.5" width="14" height="17" rx="1.5"
            stroke="rgba(200,170,90,0.85)" stroke-width="1.3" fill="rgba(200,170,90,0.06)"/>
      <line x1="7" y1="7.5" x2="15" y2="7.5" stroke="rgba(200,170,90,0.55)" stroke-width="1"/>
      <line x1="7" y1="10.5" x2="15" y2="10.5" stroke="rgba(200,170,90,0.55)" stroke-width="1"/>
      <line x1="7" y1="13.5" x2="12" y2="13.5" stroke="rgba(200,170,90,0.55)" stroke-width="1"/>
      <path d="M14.5 2.5 L18 6 L14.5 6 Z" stroke="rgba(200,170,90,0.55)" stroke-width="1" fill="rgba(200,170,90,0.1)"/>
    </svg>`,
  key: `
    <svg viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
      <circle cx="8" cy="9" r="4" stroke="rgba(200,170,90,0.85)" stroke-width="1.3" fill="none"/>
      <circle cx="8" cy="9" r="1.5" stroke="rgba(200,170,90,0.55)" stroke-width="1" fill="none"/>
      <line x1="11.5" y1="11.5" x2="19" y2="19" stroke="rgba(200,170,90,0.85)" stroke-width="1.5" stroke-linecap="round"/>
      <line x1="16" y1="17" x2="16" y2="19.5" stroke="rgba(200,170,90,0.65)" stroke-width="1.3" stroke-linecap="round"/>
      <line x1="18" y1="15.5" x2="18" y2="18" stroke="rgba(200,170,90,0.65)" stroke-width="1.3" stroke-linecap="round"/>
    </svg>`,
  default: `
    <svg viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
      <rect x="4" y="4" width="14" height="14" rx="2"
            stroke="rgba(200,170,90,0.6)" stroke-width="1.3" fill="rgba(200,170,90,0.06)"/>
      <line x1="11" y1="7" x2="11" y2="15" stroke="rgba(200,170,90,0.5)" stroke-width="1.2" stroke-linecap="round"/>
      <line x1="7" y1="11" x2="15" y2="11" stroke="rgba(200,170,90,0.5)" stroke-width="1.2" stroke-linecap="round"/>
    </svg>`
};

function renderItemIcon(item) {
  // To replace with your own drawn PNG icon:
  // return `<img src="assets/items/${item.id}.png" style="width:22px;height:22px;object-fit:contain;">`;
  return ITEM_ICONS[item.id] || ITEM_ICONS["default"];
}

function renderInventory() {
  const grid = document.getElementById("inventory-grid");
  const countEl = document.getElementById("inv-count");
  grid.innerHTML = "";

  const totalSlots = Math.max(10, Math.ceil((STATE.inventory.length + 1) / 5) * 5);

  for (let i = 0; i < totalSlots; i++) {
    const item = STATE.inventory[i];
    const slot = document.createElement("div");
    slot.className = "inv-slot" + (item ? " filled" : "");

    if (item) {
      slot.innerHTML = renderItemIcon(item);
      const tip = document.createElement("div");
      tip.className = "inv-tooltip";
      tip.textContent = item.label;
      slot.appendChild(tip);
    }

    grid.appendChild(slot);
  }

  if (STATE.inventory.length > 0) {
    countEl.textContent = STATE.inventory.length;
    countEl.style.display = "flex";
  } else {
    countEl.style.display = "none";
  }
}

function toggleInventory() {
  STATE.inventoryOpen ? closeInventory() : openInventory();
}

function openInventory() {
  STATE.inventoryOpen = true;
  const panel = document.getElementById("inventory-panel");
  panel.style.display = "block";
  requestAnimationFrame(() => panel.classList.add("open"));
}

function closeInventory() {
  STATE.inventoryOpen = false;
  const panel = document.getElementById("inventory-panel");
  panel.classList.remove("open");
  setTimeout(() => { if (!STATE.inventoryOpen) panel.style.display = "none"; }, 240);
}

function showPickupNotification(label) {
  const n = document.createElement("div");
  n.textContent = "+" + label;
  n.style.cssText = `
    position: absolute;
    bottom: 90px; right: 80px;
    font-size: 12px; letter-spacing: 0.1em;
    color: rgba(200,170,90,0.95);
    font-family: Georgia, serif; font-style: italic;
    pointer-events: none; z-index: 400;
    opacity: 1; transition: opacity 0.5s ease, transform 0.5s ease;
    transform: translateY(0);
  `;
  document.getElementById("game-container").appendChild(n);
  requestAnimationFrame(() => {
    setTimeout(() => {
      n.style.opacity = "0";
      n.style.transform = "translateY(-16px)";
      setTimeout(() => n.remove(), 500);
    }, 1200);
  });
}

// ─── TRANSITIONS ─────────────────────────────────────────────────────────────

function fadeOut(cb) {
  const f = document.getElementById("fade");
  f.style.opacity = "1";
  setTimeout(() => { if (cb) cb(); }, 700);
}

function fadeIn() {
  const f = document.getElementById("fade");
  setTimeout(() => { f.style.opacity = "0"; }, 60);
}

// ─── TOP BAR ─────────────────────────────────────────────────────────────────

function goToMainMenu() {
  closeSettings(); closeDialogue(); closeInventory(); closeLightbox();
  fadeOut(() => {
    document.getElementById("title-screen").style.display = "flex";
    document.getElementById("top-bar").style.display = "none";
    document.getElementById("inventory-btn").style.display = "none";
    document.getElementById("hotspot-layer").innerHTML = "";
    document.getElementById("prop-layer").innerHTML = "";
    document.getElementById("scene-label").textContent = "";
    bgMusic.pause(); bgMusic.currentTime = 0;
    fadeIn();
  });
}

let settingsOpen = false;
function toggleSettings() {
  settingsOpen = !settingsOpen;
  document.getElementById("settings-panel").style.display = settingsOpen ? "block" : "none";
}
function closeSettings() {
  settingsOpen = false;
  document.getElementById("settings-panel").style.display = "none";
}
function updateSettingsUI() {
  const btn = document.getElementById("music-toggle-btn");
  const slider = document.getElementById("volume-slider");
  if (btn) btn.textContent = STATE.musicEnabled ? "Music: ON" : "Music: OFF";
  if (slider) slider.value = Math.round(STATE.musicVolume * 100);
  document.getElementById("volume-readout").textContent = Math.round(STATE.musicVolume * 100) + "%";
}

// ─── EDITOR MODE ─────────────────────────────────────────────────────────────

const editorCanvas = document.getElementById("drag-canvas");
const editorCtx = editorCanvas.getContext("2d");
let drag = { active: false, x0: 0, y0: 0, x1: 0, y1: 0 };

function toggleEditor() {
  STATE.editorMode = !STATE.editorMode;
  const badge = document.getElementById("editor-badge");
  const panel = document.getElementById("editor-panel");

  if (STATE.editorMode) {
    badge.style.display = "block"; panel.style.display = "block";
    editorCanvas.style.display = "block"; editorCanvas.style.pointerEvents = "all";
    resizeEditorCanvas();
  } else {
    badge.style.display = "none"; panel.style.display = "none";
    editorCanvas.style.display = "none"; editorCanvas.style.pointerEvents = "none";
    editorCtx.clearRect(0, 0, editorCanvas.width, editorCanvas.height);
  }
  if (STATE.currentScene) renderHotspots(STATE.currentScene);
}

function resizeEditorCanvas() {
  const gc = document.getElementById("game-container");
  editorCanvas.width = gc.offsetWidth;
  editorCanvas.height = gc.offsetHeight;
}

editorCanvas.addEventListener("mousedown", e => {
  if (!STATE.editorMode) return;
  resizeEditorCanvas();
  const r = editorCanvas.getBoundingClientRect();
  drag = { active: true, x0: e.clientX - r.left, y0: e.clientY - r.top, x1: e.clientX - r.left, y1: e.clientY - r.top };
});
editorCanvas.addEventListener("mousemove", e => {
  if (!STATE.editorMode || !drag.active) return;
  const r = editorCanvas.getBoundingClientRect();
  drag.x1 = e.clientX - r.left; drag.y1 = e.clientY - r.top;
  drawEditorRect();
});
editorCanvas.addEventListener("mouseup", e => {
  if (!STATE.editorMode || !drag.active) return;
  drag.active = false;
  const r = editorCanvas.getBoundingClientRect();
  drag.x1 = e.clientX - r.left; drag.y1 = e.clientY - r.top;
  drawEditorRect(); outputEditorCoords();
});

function drawEditorRect() {
  editorCtx.clearRect(0, 0, editorCanvas.width, editorCanvas.height);
  const x = Math.min(drag.x0, drag.x1), y = Math.min(drag.y0, drag.y1);
  const w = Math.abs(drag.x1 - drag.x0), h = Math.abs(drag.y1 - drag.y0);
  editorCtx.strokeStyle = "rgba(255,200,80,0.9)"; editorCtx.lineWidth = 2;
  editorCtx.setLineDash([6, 3]); editorCtx.strokeRect(x, y, w, h);
  editorCtx.fillStyle = "rgba(255,200,80,0.07)"; editorCtx.fillRect(x, y, w, h);
}

function outputEditorCoords() {
  const W = editorCanvas.width, H = editorCanvas.height;
  const x = Math.round(Math.min(drag.x0, drag.x1) / W * 100);
  const y = Math.round(Math.min(drag.y0, drag.y1) / H * 100);
  const w = Math.round(Math.abs(drag.x1 - drag.x0) / W * 100);
  const h = Math.round(Math.abs(drag.y1 - drag.y0) / H * 100);
  document.getElementById("editor-coords").innerHTML = `x: ${x}%&nbsp;&nbsp;y: ${y}%<br>width: ${w}%&nbsp;&nbsp;height: ${h}%`;
  document.getElementById("editor-json").textContent =
`{
  "id": "hotspot_name",
  "label": "What is it?",
  "x": ${x}, "y": ${y},
  "width": ${w}, "height": ${h},
  "action": {
    "type": "dialogue",
    "speaker": "You",
    "text": "Describe what you see."
  }
}`;
}

// ─── INPUT ───────────────────────────────────────────────────────────────────

document.addEventListener("keydown", e => {
  if (e.key === "e" || e.key === "E") toggleEditor();
  if (e.key === "Escape") { closeDialogue(); closeSettings(); closeInventory(); closeLightbox(); }
  if (e.key === "i" || e.key === "I") toggleInventory();
});

document.addEventListener("mousemove", e => {
  const c = document.getElementById("custom-cursor");
  c.style.left = e.clientX + "px";
  c.style.top = e.clientY + "px";
});

document.addEventListener("click", e => {
  const settingsPanel = document.getElementById("settings-panel");
  const settingsBtn = document.getElementById("settings-btn");
  if (settingsOpen && !settingsPanel.contains(e.target) && !settingsBtn.contains(e.target)) closeSettings();

  const invPanel = document.getElementById("inventory-panel");
  const invBtn = document.getElementById("inventory-btn");
  if (STATE.inventoryOpen && !invPanel.contains(e.target) && !invBtn.contains(e.target)) closeInventory();
});

// ─── BOOT ────────────────────────────────────────────────────────────────────

renderInventory();
updateSettingsUI();
